### ISSUE TITLE
Error: No recipients defined

### ISSUE THREAD

**Issue by semateos** [semateos/meteor-redux#3]
Seems like accounts might be trying to send email upon creating a new user, but an email field isn't defined/used in the UI.

```
I20181213-10:13:03.854(-5)? Exception in setTimeout callback: { Error: No recipients defined
I20181213-10:13:03.854(-5)?     at SMTPConnection._formatError (/Users/semateos/.meteor/packages/email/.1.2.3.iwe7cd.kx5dp++os+web.browser+web.cordova/npm/node_modules/node4mailer/lib/smtp-connection/index.js:558:19)
I20181213-10:13:03.855(-5)?     at SMTPConnection._setEnvelope (/Users/semateos/.meteor/packages/email/.1.2.3.iwe7cd.kx5dp++os+web.browser+web.cordova/npm/node_modules/node4mailer/lib/smtp-connection/index.js:757:34)
I20181213-10:13:03.855(-5)?     at SMTPConnection.send (/Users/semateos/.meteor/packages/email/.1.2.3.iwe7cd.kx5dp++os+web.browser+web.cordova/npm/node_modules/node4mailer/lib/smtp-connection/index.js:394:14)
I20181213-10:13:03.855(-5)?     at PoolResource.send (/Users/semateos/.meteor/packages/email/.1.2.3.iwe7cd.kx5dp++os+web.browser+web.cordova/npm/node_modules/node4mailer/lib/smtp-pool/pool-resource.js:181:25)
I20181213-10:13:03.855(-5)?     at connect.err (/Users/semateos/.meteor/packages/email/.1.2.3.iwe7cd.kx5dp++os+web.browser+web.cordova/npm/node_modules/node4mailer/lib/smtp-pool/pool-resource.js:160:29)
I20181213-10:13:03.855(-5)?     at connection.login.err (/Users/semateos/.meteor/packages/email/.1.2.3.iwe7cd.kx5dp++os+web.browser+web.cordova/npm/node_modules/node4mailer/lib/smtp-pool/pool-resource.js:137:25)
I20181213-10:13:03.855(-5)?     at SMTPConnection._actionAUTHComplete (/Users/semateos/.meteor/packages/email/.1.2.3.iwe7cd.kx5dp++os+web.browser+web.cordova/npm/node_modules/node4mailer/lib/smtp-connection/index.js:1264:9)
I20181213-10:13:03.855(-5)?     at SMTPConnection._responseActions.push.str (/Users/semateos/.meteor/packages/email/.1.2.3.iwe7cd.kx5dp++os+web.browser+web.cordova/npm/node_modules/node4mailer/lib/smtp-connection/index.js:341:26)
I20181213-10:13:03.855(-5)?     at SMTPConnection._processResponse (/Users/semateos/.meteor/packages/email/.1.2.3.iwe7cd.kx5dp++os+web.browser+web.cordova/npm/node_modules/node4mailer/lib/smtp-connection/index.js:707:20)
I20181213-10:13:03.856(-5)?     at SMTPConnection._onData (/Users/semateos/.meteor/packages/email/.1.2.3.iwe7cd.kx5dp++os+web.browser+web.cordova/npm/node_modules/node4mailer/lib/smtp-connection/index.js:510:14)
I20181213-10:13:03.856(-5)?     at TLSSocket._socket.on.chunk (/Users/semateos/.meteor/packages/email/.1.2.3.iwe7cd.kx5dp++os+web.browser+web.cordova/npm/node_modules/node4mailer/lib/smtp-connection/index.js:658:51)
I20181213-10:13:03.856(-5)?     at emitOne (events.js:116:13)
I20181213-10:13:03.856(-5)?     at TLSSocket.emit (events.js:211:7)
I20181213-10:13:03.856(-5)?     at addChunk (_stream_readable.js:263:12)
I20181213-10:13:03.856(-5)?     at readableAddChunk (_stream_readable.js:250:11)
I20181213-10:13:03.856(-5)?     at TLSSocket.Readable.push (_stream_readable.js:208:10) code: 'EENVELOPE', command: 'API' }```

**Comment by joerou** [comment]
I couldn't replicate this one, on mine computer it just logs to the server console with the email and a line on top saying that if i want to the following email then I need to fill in the MAIL_URL env variable. See attached 
![image](https://user-images.githubusercontent.com/16531276/50099553-66326880-01ec-11e9-99e7-c594f497af61.png)

**Comment by semateos** [comment]
Looks like somehow it got an email address for your user.  Wonder how that happened...

**Comment by joerou** [comment]
Eeeuhm I got this for the signup form, with the first field is email?
<img width="745" alt="screen shot 2018-12-17 at 12 03 59 pm" src="https://user-images.githubusercontent.com/16531276/50102766-e5776a80-01f3-11e9-82cd-92b1fa8c1948.png">

**Comment by joerou** [comment]
Is your MAIL_URL env variable set locally because seems for you it is trying to actually send the email, but for me it never gets that far, only spools up the email.

Because even without a valid email address, I can't replicate your error, notice the missing "to" field, because asd is not a valid email address and I get the same message as before, that it's a dry run.

<img width="763" alt="screen shot 2018-12-17 at 12 05 42 pm" src="https://user-images.githubusercontent.com/16531276/50102854-2f605080-01f4-11e9-80bf-77c635a3baed.png">
